#!/bin/sh

PACKAGE_VERSION=$(cat package.json | jq -r .version)
GITHUB_ENDPOINT="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases"
# GITHUB_ENDPOINT_STATUSs=$(curl -v -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type:application/json" $GITHUB_ENDPOINT -d "{ \"tag_name\": \"v${PACKAGE_VERSION}\", \"target_commitish\": \"${GITHUB_SHA}\", \"name\": \"v${PACKAGE_VERSION}\", \"body\": \"Release Version ${PACKAGE_VERSION}\", \"draft\": false, \"prerelease\": false }")
GITHUB_ENDPOINT_STATUS=$(curl -H "Content-Type:application/json" $GITHUB_ENDPOINT -o /dev/null -w '%{http_code}\n' -d "{ \"tag_name\": \"v${PACKAGE_VERSION}\", \"target_commitish\": \"${GITHUB_SHA}\", \"name\": \"v${PACKAGE_VERSION}\", \"body\": \"Release Version ${PACKAGE_VERSION}\", \"draft\": false, \"prerelease\": false }" -sH "Authorization: token ${GITHUB_TOKEN}")

if [ "$GITHUB_ENDPOINT_STATUS" = "201" ]
then
  echo "This version was released"
else
  echo "There was a problem connecting to GitHub"
  exit 1
fi
