#!/bin/sh

PACKAGE_VERSION=$(cat package.json | jq -r .version)
echo $PACKAGE_VERSION
PAYLOAD="{ \
  \"tag_name\": \"v${PACKAGE_VERSION}\", \
  \"target_commitish\": \"${GITHUB_SHA}\", \
  \"name\": \"v${PACKAGE_VERSION}\", \
  \"body\": \"Release Version ${PACKAGE_VERSION}\", \
  \"draft\": false, \
  \"prerelease\": false \
}"
echo $PAYLOAD
GITHUB_ENDPOINT="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases"
echo $GITHUB_ENDPOINT
GITHUB_ENDPOINT_STATUS=$(curl -v -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type:application/json" $GITHUB_ENDPOINT -d $PAYLOAD)
echo $GITHUB_ENDPOINT_STATUS

if [ "$GITHUB_ENDPOINT_STATUS" = "200" ]
then
  echo "This version was released"
else
  echo "There was a problem connecting to GitHub"
  exit 1
fi
